src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today",message ="la date d'arrivé doit être ultérieur à la date d'aujourd'hui", groups={"front"})
     *
     * 
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath ="startDate", message="La date de départ doit être supérieur à la date d'arrivé")
     * 
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appelé à chaque fois qu'on créé une réservation
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function prePersist(){
        if (empty($this->createdAt)){
        $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    //permet de vérifier si la réservation est possible (par rapport au date)
    public function isBookableDates(){
        $notAvailableDays =$this->ad->getNotAvailableDays();

        $bookingDays = $this ->getDays();

        $formatDay = function ($day){
            return $day->format('Y-m-d');
        };

        $days           = array_map($formatDay, $bookingDays);
        $notAvailable   = array_map($formatDay, $notAvailableDays);

        foreach($days as $day){
            if (array_search($day, $notAvailable) !== false) return false;
        }

        return true;

    }

    /**
     * Permet de récupérer un tableau qui correspond à la réservation
     *
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays(){
        $result = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            86400
        );
        $days = array_map(function ($dayTimestamp){
            return new \DateTime(date('Y-m-d',$dayTimestamp));
        },$result);
        return $days;
    }


    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\dataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer){
        $this->transformer = $transformer;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée","La date à laquelle vous comptez arriver"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de depart","La date à laquelle vous comptez parter"))
            ->add('comment', TextareaType::class, $this->getConfiguration("(optionnel)","Si vous avez un commentaire, n'hésitez pas à en faire un",["required"=>false]))
        ;

        $builder ->get('startDate')->addModelTransformer($this->transformer);
        $builder ->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                'Default',
                'front'
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * 
     * @IsGranted("ROLE_USER")
     * 
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form ->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()){
            $user = $this ->getUser();

            $booking    ->setBooker($user)
                        ->setAd($ad)
            ;
            // Gestion de la disponibilité des dates
            if(!$booking->isBookableDates()){
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisi ne sont pas disponible !"
                );
            } else {
                $manager->persist($booking);
                $manager->flush();
    
                return $this->redirectToRoute('booking_show', ['id' =>$booking->getId(), 'withAlert' => true]);
            
            }
            
        }
        
        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une réservation
     * 
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request,  EntityManagerInterface $manager){

        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $user   = $this ->getUser();
            $ad     = $booking->getAd();

            $comment    ->setAuthor($user)
                        ->setAd($ad)
            ;

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte !"
            );
            
            
        }

        return $this-> render('booking/show.html.twig', [
            'booking'   => $booking,
            'form'      => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ ad.title }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
{% endblock %}
{% block body %}
<div class="jumbotron">
    <h1 class="display-4">Réservation : {{ ad.title }}</h1>
    <hr class="my-4">
    <p>Vous êtes sur le point de réserver le bien de <strong> {{ ad.author.getFullName }}</strong>, dites nous tout, on s'occupe du reste !</p>
</div>
<div class="container my-5">

{{ form_start(form) }}
    <div class="alert alert-light">
        <h2>Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>

        <div class="row">
            <div class="col">{{ form_row(form.startDate) }}</div>
            <div class="col">{{ form_row(form.endDate) }}</div>
        </div>
        <h4 class="my-3">Montant du séjour : <span id="amount">...</span> &euro;</h4>
        <p><span id="days">0</span> nuits à {{ad.price | number_format(2, ',' ,' ') }} &euro; /nuit</p>
    </div>




    <h2>Vous avez un commentaire ?</h2>
{{ form_row(form.comment) }}

    <button type="submit" class="btn btn-success">Réserver</button>
{{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" charset="UTF-8"></script>

<script>
    $(document).ready(function(){
        $.fn.datepicker.dates['fr'] = {
            days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
            daysShort: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
            daysMin: ["Di", "Lu", "Ma", "Me", "Je", "Ve", "Sa"],
            months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
            monthsShort: ["Jan", "Fev", "Mar", "Avr", "Mai", "Jui", "Jul", "Aou", "Sep", "Oct", "Nov", "Dec"],
            today: "Aujourd'hui",
            clear: "Reset",
            format: "dd/mm/yyyy",
            titleFormat: "MM yyyy" /* Leverages same syntax as 'format' */
            
        };
        $('#booking_startDate, #booking_endDate').datepicker({
            format:'dd/mm/yyyy',
            datesDisabled : [
                {% for day in ad.getNotAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                {% endfor %}
            ], 
            startDate : new Date(),
            language : "fr",
            weekStart: 1
        });

        $('#booking_startDate, #booking_endDate').on('change',calculateAmount);
    });

    function calculateAmount(){
        
        const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
        const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));

        if (startDate && endDate && startDate < endDate){
            const DAY_TIME = 24*60*60*1000;
            const interval = endDate.getTime() - startDate.getTime();
            const days = interval / DAY_TIME;
            const amount = days * {{ ad.price }};

            $('#days').text(days);
            $('#amount').text(amount.toLocaleString('fr-FR'));
        }
    }
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{booking.id}}{% endblock %}

{% block body %}

{% set ad = booking.ad %}
{% set author = ad.author %}
<div class="container my-5">
    <h1 class="display-4">Votre réservation n°{{booking.id}}</h1>
    
    {% if app.request.query.get('withAlert') %}
        <div class="alert alert-success">
            <h4 class="alert-heading">Bravo !</h4>
            <p>Votre réservation auprès de <strong><a href="{{ path("user_show", {'slug' : author.slug})}}">{{ author.getFullName}}</a></strong> pour l'annonce <strong><a href="{{ path('ads_show' , {'slug' : ad.slug})}}">{{ ad.title }}</a></strong> à bien été prise en compte !</p>
        </div>
    {% endif %}
        <div class="row">
            <div class="col-md">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Détails</h2>
                    <dl class="row">
                        <dt class="col-xl-4">Numéro</dt>
                        <dd class="col-xl-8">{{ booking.id }}</dd>
                        <dt class="col-xl-4">Date d'arrivée</dt>
                        <dd class="col-xl-8">{{ booking.startDate | date('d/m/y') }}</dd>
                        <dt class="col-xl-4">Date de départ</dt>
                        <dd class="col-xl-8">{{ booking.endDate | date('d/m/y') }}</dd>
                        <dt class="col-xl-4">Nombre de nuits</dt>
                        <dd class="col-xl-8">{{ booking.duration }}</dd>
                        <dt class="col-xl-4">Montant total</dt>
                        <dd class="col-xl-8">{{ booking.amount | number_format(2, ',' ,' ') }} &euro;</dd>
                        <dt class="col-xl-4">Commentaire événtuel</dt>
                        <dd class="col-xl-8">{{ booking.comment|default ('Pas de commentaires') }}</dd>
                    </dl>
                </div>
            </div>
            <div class="col-md">
                <div class="alert alert-light">
                <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{ author.picture}}" class="avatar avatar-medium" alt="Avatar de {{ author.getFullName }}">
                        </div>
                        <div class="col-md">
                        <h4>
                            <a href="{{ path('user_show',{'slug': author.slug}) }}">{{ author.getFullName }}</a>
                        </h4>
                            <span class="badge badge-primary">{{author.ads | length }} annonce{% if (author.ads | length)>1 %}s{% endif %}</span>
                        </div>
                    </div>
                    <div class="my-3">
                    {{ author.introduction | raw }}
                    </div>

                    <a href="{{ path('user_show',{'slug': author.slug}) }}" class="btn btn-primary">Plus d'info sur {{ author.firstName }}</a>
                    
                    <hr>
                    <h2 class="alert-heading">Votre hébergement</h2>
                    <h4>    
                        <a href="{{ path('ads_show',{'slug': ad.slug}) }}">{{ad.title}}</a>
                    </h4>
                    <img src="{{ ad.coverImage }}" alt="Image de {{ad.title}}" class="img-fluid">
                    
                    <div class="my-3">
                    {{ad.introduction | raw }}
                    </div>
                    
                    <a href="{{ path('ads_show',{'slug': ad.slug}) }}" class="btn btn-primary">Plus d'info</a>
                </div>
                <div class="alert alert-light" id="comment">
                    
                    {% if date()> date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                        <h2 class="alert-heading">Votre commentaire : </h3>
                            <blockquote>
                                 {{ comment.content }}
                            </blockquote>
                            {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                        {% else %}
                        <h2 class="alert-heading">Votre avis compte !</h2>
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <button type="submit" class="btn btn-success">Confirmer</button>
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                    <h2 class="alert-heading">Votre avis compte !</h2>
                        <p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas terminer</p>
                    {% endif %}

                </div>
            </div>
        </div>


</div>
{% endblock %}