src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;

use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà ce titre"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage ="Le titre doit faire plus de 10 caractères", maxMessage="Le titre ne peut pas faire plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     * 
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, minMessage ="L'introduction doit faire plus de 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage ="La description doit faire plus de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */

    public function initializeSlug(){
        if (empty($this->Slug)){
            $slugify = new Slugify();
            $this->slug= $slugify->slugify($this->title);
        }
    }
    
    /**
     * Permet de récupérer le commentaire d'un author par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment){
            if ($comment->getAuthor() === $author) return $comment;
            
        }
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return void
     */
    public function getAvgRatings()
    {
        $sum = array_reduce($this->comments->toArray(), function($total,$comment){
            return $total + $comment->getRating();
        },0);
        if(count($this->comments)>0) return  $sum / count($this->comments);

        return 0;
        
    }
    
    /**
     * Cette fonction permet d'optenir un tableau des jours qui ne sont pas disponible
     *
     * @return array Un tableau d'objet DateTime représentant les jours d'occupations
     */
    public function getNotAvailableDays(){
        $notAvailableDays =[];

        foreach( $this->bookings as $booking){
            $result = range(    $booking->getStartDate()->getTimestamp(),
                                $booking->getEndDate()->getTimestamp(),
                                86400
            );

            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            }, $result);

            $notAvailableDays = array_merge($notAvailableDays,$days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Image;
use App\Form\AdNewType;
use App\Repository\AdRepository;
use App\Service\PaginationService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads/{page<\d+>?1}", name="ads_index")
     */
    public function index(AdRepository $repo, PaginationService $pagination, $page)
    {

        $pagination ->setEntityClass(Ad::class)
                    ->setPage($page)
                    ->setLimit(12);

        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
            'pagination' => $pagination
        ]);
    
    }


    /**
     * Permet de créé une annonce
     *
     * 
     * 
     * @Route("ads/new", name="ads_create")
     * 
     * @IsGranted("ROLE_USER")
     * 
     */
    public function create(Request $request, EntityManagerInterface $manager){
        $ad = new Ad();

        $form = $this   ->createForm(AdNewType::class,$ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $manager -> persist($image);
            }

            $ad->setAuthor($this->getUser());

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );

            return $this ->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }
        

        return $this -> render('ad/new.html.twig',[
            'form' => $form->createView()
        ]);

    }
/**
 * Permet d'afficher le formulaire d'édition
 * 
 * @Route("ads/{slug}/edit", name="ads_edit")
 *
 * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vout appartient pas, vous ne pouvez pas la modifier")
 * 
 */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager){

        
        $form = $this   ->createForm(AdNewType::class,$ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $manager -> persist($image);
            }
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modifié !"
            );

            return $this ->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this-> render('ad/edit.html.twig',[
            'form' => $form->createView(), 
            'ad' => $ad
        ]);
    }

    /**
     * Permet d'afficher une seule annonce
     *
     * @Route("/ads/{slug}", name="ads_show")
     */
    public function show(Ad $ad){
        return $this -> render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    
    
    }

    /**
     * Permet de suprimer une annonce
     * 
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * 
     * @Security("is_granted('ROLE_USER') and user == ad.getAuthor()" , message="Vous n'avez pas le droit d'accéder à cette ressource")
     *
     * 
     * @param Ad $ad
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $manager){

        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success', "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute("ads_index");
    }

}

templates/ad/_ad.html.twig
{% set url = path('ads_show',{'slug':ad.slug}) %}
            <div class="col-md-4 mt-3">
                <div class="card-header text-center">
                    {{ ad.rooms }} chambres, <strong> {{ ad.price | number_format(2, ',' ,' ')  }}&euro; / nuit</strong> </br>
                    {% if ad.comments | length > 0 %}
                        <small>{% include 'partials/rating.html.twig' with {'rating' : ad.avgRatings} %}</small>
                        <br>
                        <small class="">{{ ad.comments | length }} avis !</small>
                    {% else %}
                        <small>Pas encore noté</small>
                    {% endif %}
                    
                    <a href="{{ url }}" class="overflow-hidden d-block" title="Voir l'annonce">
                        <img src="{{ ad.coverImage }}" class="" alt="Image de l'annonce" style="height:200px">
                    </a>
                    <div class="card-body">
                        <a href="{{ url }}" title="Voir l'annonce">
                            <h4 class="card-title">
                                {{ ad.title }}
                            </h4>
                        </a>
                        <p class="card-text">
                            {{ ad.introduction }}
                        </p>
                        <a href="{{ path('ads_show',{'slug':ad.slug}) }}" class="btn btn-primary mt-3" title="Voir l'annonce">En savoir plus</a>
                        {% if app.user and app.user == ad.author %}
                        <a href="{{ path('ads_edit', {'slug':ad.slug}) }}" class="btn btn-primary mt-3">Modifier l'annonce</a>
                        {% endif %}
                    </div>
                </div>
            </div>

templates/ad/_collection.html.twig
{% block _ad_new_images_widget %}

    <small>Ici, vous pouvez ajouter vos propres images !</small>

    {{ form_widget(form) }}

<input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-info"><i class="fas fa-plus"></i></button>
    </div>

{% endblock %}

{% block _ad_new_images_entry_row %}

    {{ form_widget(form) }}

{% endblock %}

{% block _ad_new_images_entry_widget %}

    <div class="form-group" id="block_{{ id }}">
    <div class="row mb-4">
        <div class="col-10">
            <div class="row">
                <div class="col-sm my-2">
                    {{ form_widget(form.url)}}
                    {{ form_errors(form.url)}}
                </div>
                <div class="col-sm my-2">
                    {{ form_widget(form.caption)}}
                    {{ form_errors(form.caption)}}
                </div>
            </div>
        </div>
        <div class="col-2 d-flex justify-content-center align-items-center">
            <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger"> <i class="fas fa-minus"></i> </button>
        </div>
    </div>
    </div>

{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="jumbotron">
    <h1 class="display-4">Modifier l'annonce : {{ ad.title }}</h1>
    <hr class="my-4">
</div>
<div class="container">

 {{ form_start(form) }}

                <div class="row">
                    <div class="col-md">
                        <div class="alert alert-light">
                            <h2>Informations générales</h2>
                            <hr>
                            {{ form_row(form.title) }}
                            {{ form_row(form.slug) }}
                            {{ form_row(form.price) }}
                            {{ form_row(form.rooms) }}

                        </div>
                        <div class="alert alert-light">
                            <h2>Détails de l'annonce</h2>
                            <hr>
                            {{ form_row(form.introduction) }}
                            {{ form_row(form.content) }}
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="alert alert-light">
                            <h2>Images de l'annonce</h2>
                            <hr>
                            {{ form_row(form.coverImage) }}
                            {{ form_row(form.images) }}
                        </div>
                    </div>
                </div>


            <button type="submit" class="btn-block btn-primary py-3 rounded">Modifier</button>
            {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('ad') }}

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonce{% endblock %}

{% block body %}
<div class="jumbotron">
    <h1 class="display-4">Voici les annonces de nos hôtes</h1>
    <hr class="my-4">
</div>
<div class="container">
    <div class="row">
    
    {% for ad in pagination.data %}
        {% include 'ad/_ad.html.twig' %}
    {% endfor %}
    </div>
    <div class="my-5">
    
    {{ pagination.display() }}
    </div>
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créations d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="jumbotron">
    <h1 class="display-4">Créé une nouvelle annonce</h1>
    <hr class="my-4">
</div>
<div class="container">
{{ form_start(form) }}

    <div class="row">
        <div class="col-md">
            <div class="alert alert-light">
                <h2>Informations générales</h2>
                <hr>
                {{ form_row(form.title) }}
                {{ form_row(form.slug) }}
                {{ form_row(form.price) }}
                {{ form_row(form.rooms) }}

            </div>
            <div class="alert alert-light">
                <h2>Détails de l'annonce</h2>
                <hr>
                {{ form_row(form.introduction) }}
                {{ form_row(form.content) }}
            </div>
        </div>
        <div class="col-md">
            <div class="alert alert-light">
                <h2>Images de l'annonce</h2>
                <hr>
                {{ form_row(form.coverImage) }}
                {{ form_row(form.images) }}
            </div>
        </div>
    </div>


<button type="submit" class="btn-block btn-primary py-3 rounded">Créer</button>
{{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('ad') }}
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}

<div class="ad-title" style="background-image: url({{ ad.coverImage }}); background-size:cover;background-position:center center;">
    <div style="background:rgba(255,255,255,0.5)">
        <div class="container py-5" >
            <h1 class="">{{ ad.title }}</h1>
            <p class="text-dark"> {{ad.introduction}}</p>
            <p class="h2 my-5">
                <strong>{{ad.rooms }} chambres</strong> pour <strong class="display-4">{{ad.price | number_format(2, ',' ,' ') }}&euro;</strong>/nuit
            </p>
            <a href="{{ path('booking_create', {'slug':ad.slug}) }}" class="btn-lg btn-primary">Réserver</a>
            {% if app.user and app.user == ad.author %}
            <a href="{{ path('ads_edit', {'slug':ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
            
            <a href="{{ path('ads_delete', {'slug':ad.slug}) }}" class="btn btn-danger" onclick="return confirm(`Êtes vous sur de vouloir de supprimer l'annonce : {{ ad.title }} ?`)">Supprimer</a>
            {% endif %}
        </div>
    </div>
</div>

<div class="container py-5">
    <div class="row">
        <div class="col-lg-8 mb-3">
            {{ad.content | raw}}
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                {% for image in ad.images %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" class="{% if loop.first %}active{% endif %}"></li>
                {% endfor %}
                    
                </ol>
                <div class="carousel-inner">
                {% for image in ad.images %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <img src="{{ image.url }}" class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block" style="color:white; text-shadow:3px 3px 3px rgba(0,0,0,0.8)">
                                <h5 class="text-light">{{ ad.title }}</h5>
                                <p>{{image.caption}}</p>
                            </div>
                    </div>
                {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <hr/>
            {% if ad.comments | length > 0 %}
                <h2 class="mb-3">Commentaires de nos voyageurs :</h2>

                <div class="alert alert-info">
                    <h4 class="alert-heading">
                        <div class="row align-items-center">
                            <div class="col-sm">Note global donnée par nos voyageurs <br>
                            </div>
                            <div class="col-sm text-right">
                            {{ ad.AvgRatings | round(1) }}
                                {% include 'partials/rating.html.twig' with {'rating' : ad.AvgRatings } %} <br>
                                <small class="">{{ ad.comments | length }} avis !</small>
                            </div>
                        </div>
                    </h4>
                </div>
                {% for comment in ad.comments %}
                    <div class="border-bottom border-light mb-3 p-3">
                        <strong class="h5">{{ comment.author.getFullName }}</strong> a dit :
                        <br>
                        <small> {{ comment.createdAt | date ('d/m/Y') }}</small>
                        <blockquote class="my-3">
                            {{ comment.content }}
                        </blockquote>
                        <strong>Note donnée par {{comment.author.firstName }} : </strong>
                        {% include 'partials/rating.html.twig' with {'rating' : comment.rating} %}
                    </div>
                {% endfor %}
            {% else %}
                <h2>Cette annonce n'a pas encore reçue de commentaire</h2>
            {% endif %}
        </div>
        <div class="col">
        {% set a = ad.author %}
            <div class="d-flex justify-content-start align-items-center flex-wrap">
                <div class="mr-3">
                <a href="{{ path('user_show', {'slug': a.slug}) }}">
                    <img src="{{ a.picture }}" class="avatar avatar-medium d-block" alt="Avatare de {{ a.getFullName }}" style="max-width:64px; max-heigth:64px;">
                </a>
                </div>
                <div class="mb-3">
                <a href="{{ path('user_show', {'slug': a.slug}) }}">
                    <h3>{{ a.getFullName }}</h3>
                </a>
                    <span class="badge badge-primary">{{ a.ads | length }} annonce{% if (a.ads | length)>1 %}s{% endif %} </span>
                </div>
                {{ a.description | raw }}
            </div>
        </div>
    </div>

</div>
{% endblock %}